baseurl: https://example.com/
title: Clarity
author: Jane Doe
copyright: Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved.
paginate: 10
theme: hugo-clarity
disqusShortname: ''
DefaultContentLanguage: en
taxonomies:
  category: categories
  series: series
  tag: tags
markup:
  goldmark:
    extensions:
      typographer: no
    renderer:
      hardWraps: no
      unsafe: yes
      xhtml: no
  highlight:
    codeFences: yes
    guessSyntax: yes
    hl_Lines: --
    lineNoStart: 1
    lineNos: yes
    lineNumbersInTable: no
    noClasses: no
    tabWidth: 2
params:
  author: Jane Doe
  centerLogo: no
  codeLineNumbers: no
  codeMaxLines: 7
  enableMathNotation: no
  enforceLightMode: no
  fallBackOgImage: images/thumbnail.png
  figurePositionLabel: Figure
  figurePositionShow: no
  ga_analytics: XXXXXXXXXX
  introDescription: Technologist, perpetual student, teacher, continual incremental
    improvement.
  languageMenuName: "\U0001F310"
  largeTwitterCard: no
  logo: logos/logo.png
  mainSections: post
  mobileNavigation: left
  numberOfTagsShown: 14
  twitter: '@janedoe'
